context:
  version: 0.5.8

package:
  name: statix
  version: ${{ version }}

source:
  url: https://github.com/oppiliappan/statix/archive/v${{ version }}.tar.gz
  sha256: 547ee83df5814c18f8577b5ca25a1f12a416900b6eaa95821386a28090e8a89d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - statix --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: lints and suggestions for the nix programming language
  homepage: https://github.com/oppiliappan/statix
  repository: https://github.com/oppiliappan/statix

extra:
  recipe-maintainers:
    - danielnachun
